export default {
  nautilusChainTestnet: 91002,
  nautilus_rpc_testnet: "https://triton.api.nautchain.xyz",
  polygon_zkevm_testnet:1442,
  polygonzkevm_rpc_testnet:"https://rpc.public.zkevm-test.net",
  chainId: 1,
  chainIdTestnet: 42,
  bscChain: 56,
  bscChainTestent: 97,
  hmy_rpc_mainnet: "https://api.harmony.one",
  hmy_rpc_testnet: "https://api.s0.b.hmny.io",
  hmyChainTestnet: 1666700000,
  hmyChainMainnet: 1666600000,
  polygon_rpc_testnet: "https://mumbai-explorer.matic.today", // matic testnet rpc
  polygon_chain_mainnet: 137,
  polygon_chain_testnet: 80001,
  api: "http://localhost:8020",
  coingecko: "https://api.coingecko.com/api",
  arbitrumChain: 42161,
  arbitrumRpc: "https://arbitrum-mainnet.infura.io/v3/898b1725b971464bbca3f7023dd5f8a0",
  arbitrumGoerliChain: 421613,
  arbitrumGoerliRpc: "https://goerli-rollup.arbitrum.io/rpc",
};
